<a href="https://colab.research.google.com/github/SangeethaPaulraj26/DataScience/blob/main/Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import glob
import re
import math


**Create Series from Numpy array**

In [2]:
v = np.array([1,2,3,4,5,6,7,8,9])
s1 =pd.Series(v)
s1


0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

**Datatype of Series**

In [3]:
s1.dtype

dtype('int64')

**Number of bytes**


In [4]:
s1.nbytes

72

** shape of series**

In [6]:
s1.shape


(9,)

** number of dimensions**

In [8]:
s1.ndim

1

In [9]:
# Length of Series
len(s1)


9

In [10]:
s1.count()


9

In [11]:
# Create Series from list
s0 = pd.Series([1,2,3], index = ['a','b','c'])
s0


a    1
b    2
c    3
dtype: int64

In [13]:
# Modifying index in Series
X= np.array(['a','b','c','d','e','f','g','h','i'])
s1.index = X
s1


a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int64

In [14]:
# Creating series using Random and Range function
v2 = np.random.random(10)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
v2


array([0.42735936, 0.76903208, 0.64536476, 0.42256837, 0.84781586,
       0.09234789, 0.54656079, 0.21980513, 0.63215549, 0.06279547])

In [15]:
ind2,v2


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([0.42735936, 0.76903208, 0.64536476, 0.42256837, 0.84781586,
        0.09234789, 0.54656079, 0.21980513, 0.63215549, 0.06279547]))

In [16]:
dict = {'a1':10, 'a2':20, 'a3':30, 'a4':40}
s3 = pd.Series(dict)
s3


a1    10
a2    20
a3    30
a4    40
dtype: int64

In [17]:
pd.Series(99, index = [0,1,2,3,4,5])


0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [18]:
#Series with Pandas:Slicing Series
s

0    0.427359
1    0.769032
2    0.645365
3    0.422568
4    0.847816
5    0.092348
6    0.546561
7    0.219805
8    0.632155
9    0.062795
dtype: float64

In [19]:
# Return all elements of the series
s[:]


0    0.427359
1    0.769032
2    0.645365
3    0.422568
4    0.847816
5    0.092348
6    0.546561
7    0.219805
8    0.632155
9    0.062795
dtype: float64

In [20]:
# First three element of the Series
s[0:3]

0    0.427359
1    0.769032
2    0.645365
dtype: float64

In [21]:
# Last element of the Series
s[-1:]

9    0.062795
dtype: float64

In [22]:
# Fetch first 4 elements in a series
s[:4]


0    0.427359
1    0.769032
2    0.645365
3    0.422568
dtype: float64

In [23]:
# Return all elements of the series except last two elements.
s[:-2]


0    0.427359
1    0.769032
2    0.645365
3    0.422568
4    0.847816
5    0.092348
6    0.546561
7    0.219805
dtype: float64

In [24]:
# Return all elements of the series except last element.
s[:-1]


0    0.427359
1    0.769032
2    0.645365
3    0.422568
4    0.847816
5    0.092348
6    0.546561
7    0.219805
8    0.632155
dtype: float64

In [25]:
# Return last two elements of the series
s[-2:]

8    0.632155
9    0.062795
dtype: float64

In [26]:
# Return last element of the series
s[-1:]

9    0.062795
dtype: float64

In [27]:
s[-3:-1]


7    0.219805
8    0.632155
dtype: float64

In [28]:
# Append Series
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int64

In [29]:
s3


a1    10
a2    20
a3    30
a4    40
dtype: int64

In [34]:
# Append S2 & S3 Series
s4 = pd.concat([s2, s3])
s4


a      1
b      2
c      3
d      4
e      5
f      6
g      7
h      8
i      9
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [35]:
# When "inplace=False" it will return a new copy of data with the operation per
s4.drop('a4', inplace=False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
h      8
i      9
a1    10
a2    20
a3    30
dtype: int64

In [36]:
# When we use "inplace=True" it will affect the dataframe
s4.drop('a4', inplace=True)
s4


a      1
b      2
c      3
d      4
e      5
f      6
g      7
h      8
i      9
a1    10
a2    20
a3    30
dtype: int64

In [41]:
s4 = pd.concat([s4, pd.Series({'a4': 7})])
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
h      8
i      9
a1    10
a2    20
a3    30
a4     7
a4     7
dtype: int64

In [42]:
#Operation on Series
v1 = np.array([10,20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1, s2

(0    10
 1    20
 2    30
 dtype: int64,
 0    1
 1    2
 2    3
 dtype: int64)

In [43]:
# Addition of two series
s1.add(s2)


0    11
1    22
2    33
dtype: int64

In [44]:
# Subtraction of two series
s1.sub(s2)


0     9
1    18
2    27
dtype: int64

In [45]:
# Subtraction of two series
s1.subtract(s2)


0     9
1    18
2    27
dtype: int64

In [47]:
# Increment all numbers in a series by 8
s1.add(8)


0    18
1    28
2    38
dtype: int64

In [48]:
# Multiplication of two series
s1.mul(s2)


0    10
1    40
2    90
dtype: int64

In [49]:
# Multiply each element by 1000
s1.mul(1000)

0    10000
1    20000
2    30000
dtype: int64

In [50]:
# Division
s1.divide(s2)


0    10.0
1    10.0
2    10.0
dtype: float64

In [51]:
# MAX number in a series
s1.max()


30

In [52]:
# Min number in a series
s1.min()


10

In [53]:
# Average
s1.mean()
# median
s1.median()

20.0

In [54]:
# Standard Deviation
s1.std()

10.0

In [55]:
# Series comparison
s1.equals(s2)


False

In [56]:
# Series comparison
s1.equals(s4)


False

In [57]:
s5 = pd.Series([1,1,2,2,3,3], index = [0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [58]:
# afind frequency
s5.value_counts()

1    2
2    2
3    2
Name: count, dtype: int64